services:
  node:
    build:
      context: .
    working_dir: /phonebook
    ports:
      - "5173:5173"
      - "3001:3001"
    volumes:
      - .:/phonebook
      - node_modules:/usr/src/phonebook/node_modules
    command: ["npm", "run", "start"]
volumes:
  node_modules:
