services:
  node:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/phonebook
      - node_modules:/usr/src/phonebook/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  node_modules: